apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: python
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "35915"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - env:
        - name: APP_ID
          value: python
        - name: APP_CHANNEL_ADDRESS
        - name: DAPR_METRICS_PORT
          value: "35915"
        image: ariqmbrilian/public-image:python
        imagePullPolicy: Always
        name: python
        resources: {}
