apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak-workflows
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ak-workflows
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: ak-workflows
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "42533"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: ak-workflows
    spec:
      containers:
      - env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_METRICS_PORT
          value: "42533"
        - name: APP_ID
          value: ak-workflows
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "8080"
        image: andalregistry2.azurecr.io/orchestrator.api:orchestrator-api-temp
        imagePullPolicy: Always
        name: ak-workflows
        ports:
        - containerPort: 8080
        resources: {}
