apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://192.168.24.130:9411/api/v2/spans"

# https://docs.dapr.io/operations/observability/tracing/zipkin/